name: Build, Push & Scan Docker Image to AWS ECR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build & Push Docker Image to AWS ECR
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{secrets.AWS_REGION}} 
      ECR_REPOSITORY: my-app
      IMAGE_TAG: latest
      IMAGE_URI: 313616258649.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
      GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
      SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        aws-region: ${{secrets.AWS_REGION}} 

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t my-app:latest .

    - name: Tag Docker image
      run: |
        docker tag my-app:latest $IMAGE_URI
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
          image-ref: my-app:latest
          output: trivy-report.json
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

    - name: Push image to Amazon ECR
      run: |
        docker push $IMAGE_URI

    - name: Start image scan
      run: |
        aws ecr start-image-scan \
          --repository-name my-app \
          --image-id imageTag=latest

    - name: Wait and get image scan findings
      run: |
        sleep 15
        aws ecr describe-image-scan-findings \
          --repository-name my-app \
          --image-id imageTag=latest

    - name: Upload Vulnerability Scan Results
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report
        path: trivy-report.json
        retention-days: 1

    # - name: SonarQube Scan
    #   uses: SonarSource/sonarqube-scan-action@v4.1.0 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
    #     SONAR_HOST_URL: https://sonarcloud.io/
   